import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './components/navbar'
import Banner from './components/banner';
import '../app/styles/styles.css'
import CaseStudies from './components/casestudies';
import Services from './components/services';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='LandingPage'>
        <Navbar/>
        <Banner />
        </div>
        <div><CaseStudies /></div>
        <div>
          <Services/>
        </div>
        {children}</body>
    </html>
  )
}
